### PR TITLE
Update @actions/core to 1.10.0

### PR DESCRIPTION
**Pull request by metzgegu**
**Hello** 👋 

This PR update `@actions/core`to version `1.10.0` in order to use the [file version](https://github.com/actions/toolkit/pull/1178) of `save-state` and `set-output` workflow commands.

It will remove this warning when using this github action:

Capture d’écran 2022-10-17 à 15 56 48

Thank you 😄

### CODE REVIEW

**Comment by metzgegu** [comment]
👋 @SvanBoxel  
Do you have some time to review this ?

**Comment by SvanBoxel** [comment]
Thanks for the ping! Reviewing now. @metzgegu

**Review by SvanBoxel — APPROVED** [review]

**Comment by metzgegu** [comment]
Thanks @SvanBoxel 😄
Could you release a new patch/minor version of this action ? or when do you plan to release a new version ?

**Comment by metzgegu** [comment]
👋 @SvanBoxel
Any plan for releasing a new version ? `set-output` command will be removed on 31st May 2023: [GitHub changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Pull request merged**
